module.exports.MessageHeader = {

    MSG_HELLO_NOT_CONFIRMED: "999",
    MSG_HELLO_CONFIRMED: "100",
    MSG_REFRESH_RECEIVED: "888",
    MSG_REFRESH_NOT_RECEIVED: "777",
    MSG_CONFIGURING_PINS: "101",
    MSG_UPLOADING_FIRMWARE: "102",
    MSG_STARTING_SYSTEM: "111"
} 